//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment1_WebDev.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FunIdeaDetails
    {
        public string detailsID { get; set; }
        public string ideaID { get; set; }
        public string reference { get; set; }
        public System.DateTime updateDate { get; set; }
        public string largeImg { get; set; }
        public string imgCaption { get; set; }
        public string contentSummarization { get; set; }
    
        public virtual FunIdeas FunIdea { get; set; }
    }
}
