//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment1_WebDev.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FunIdeas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FunIdeas()
        {
            this.FunIdeaDetails = new HashSet<FunIdeaDetails>();
        }
    
        public string ideaID { get; set; }
        public string ideaTitle { get; set; }
        public string thumbnail { get; set; }
        public string imgCaption { get; set; }
        public string ideaDescription { get; set; }
        public string category { get; set; }
        public bool toDo { get; set; }
        public Nullable<int> difficultyLevel { get; set; }
        public string ideaComment { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FunIdeaDetails> FunIdeaDetails { get; set; }
    }
}
